### ISSUE TITLE
Copy Code icon in editor AND preview view

### ISSUE THREAD

**Issue by JohnnyMT** [ckant/joplin-plugin-better-code-blocks#2]
Hi Chris, 
thanks a lot for this plugin, I like it very much!

One idea to make it even better:
I only see the "copy code" icon in the "editor view". 
All other "copy code plugins" show it only in the "preview view".

Would be great to have it in both views! :-)

How do you think about this idea?

Have a great day ahead! 😄

**Comment by ckant** [comment]
Is there a reason to not enable both plugins? The note editor and the rendered preview are actually two separate plugin types and I'm currently only targeting the editor. It's possible to target both, but I thought the existing other plugins met the need.

**Comment by JohnnyMT** [comment]
Hm yesterday it didn't work when both were enabled, only the last enableded one worked, even thou I restarted Joplin... Today it works with both, therefore I close this issue.
Thanks for your help and thanks again für the Plugin!!
