### ISSUE TITLE
Feature request: tabbed code blocks

### ISSUE THREAD

**Issue by pa-0** [ckant/joplin-plugin-better-code-blocks#4]
Is it even possible?

**Comment by ckant** [comment]
Definitely possible (and useful), but not part of the typical (github/commonmark) markdown spec.

There are some markdown renderers that support this stuff like [PyMdownX](https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/tab/#tab).

Unfortunately, Joplin does not support any syntax like this and it's not something I would look to add unless it did.

https://joplinapp.org/help/apps/markdown/

[I did find some discussion on github requesting this be added.](https://github.com/github/markup/issues/1552) Seems like that traction would be needed before any of the renderers would begin to adopt it.

**Comment by pa-0** [comment]
Thanks
