### ISSUE TITLE
Not working with Joplin version > 3.x

### ISSUE THREAD

**Issue by Heart1010** [ckant/joplin-plugin-better-code-blocks#5]
Is there an update planned to support the newer Joplin version > 3.x?

This is what I get at the moment:
![image](https://github.com/user-attachments/assets/b91a69e5-eb36-4c28-b299-46635834d0be)

Thanks 👍

**Comment by ckant** [comment]
No update planned, unfortunately, as I'm not using Joplin currently.

I believe Joplin is updating from CodeMirror 5 to 6 for the markdown editor, which is a pretty big rewrite as the v6 APIs are quite different.

**Comment by Heart1010** [comment]
> No update planned, unfortunately, as I'm not using Joplin currently.
> 
> I believe Joplin is updating from CodeMirror 5 to 6 for the markdown editor, which is a pretty big rewrite as the v6 APIs are quite different.

That's a shame, of course, but I understand the decision. Maybe another developer will take over the work... 👍

**Comment by ckant** [comment]
I've actually started working on supporting Joplin v3 (CodeMirror 6). Should be releasing it soon.

**Comment by AlbertBaubleDeem** [comment]
> I've actually started working on supporting Joplin v3 (CodeMirror 6). Should be releasing it soon.

I just came to this repo to offer help or fork it. Thank you so much for getting back to it! Let me know if you might use a PR for any part.

**Comment by ckant** [comment]
Just pushed the update. The plugin now works with Joplin 3.x / CodeMirror 6!

**Comment by Heart1010** [comment]
The screenshot/warning (1st post) is still there - where does it came from?

**Comment by ckant** [comment]
Ah thanks, yeah the Joplin code is [hardcoded to show that warning](https://github.com/laurent22/joplin/blob/13f71e713c62b1e912c488cb771025a48961332b/packages/app-desktop/gui/NoteEditor/WarningBanner/WarningBanner.tsx#L41).

Just submitted an issue to remove it:
https://github.com/laurent22/joplin/issues/11451

You can safely dismiss the warning banner, as it's just informational. Hopefully the plugin can be taken off the "warning list" for the next Joplin release.

**Comment by executed** [comment]
@ckant 
One minor question: am I mistaken, or was there a copy button on the view-only side of the MD editor?
Thank you very much for the update!! There is so much work in PR, hats off...

**Comment by ckant** [comment]
> @ckant One minor question: am I mistaken, or was there a copy button on the view-only side of the MD editor? Now I only see it in the editor side when hovering over the code block.

This plugin was only for the markdown editor, [but there's another plugin that adds a copy button to the preview](https://joplinapp.org/plugins/plugin/com.joplin.copy.codeBlocks/).

**Comment by executed** [comment]
@ckant Perfect! Thank you very much!
My nerdy notes are somewhat looking good again!!
