### ISSUE TITLE
Option to add syntax highlighting for rare languages

### ISSUE THREAD

**Issue by chr15m** [ckant/joplin-plugin-better-code-blocks#7]
Like the exclude functionality it would be great to be able to add languages. They could pull the highlighting from CDN. E.g. adding "clojure" to the list would inject this:

https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/mode/clojure/clojure.min.js

**Comment by ckant** [comment]
The languages supported for syntax highlighting [were whitelisted in the Joplin code.](https://github.com/laurent22/joplin/blob/145cb6c41e166e5f1d75f4c190acc19c9f55d7c1/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx#L37-L80)

This was the case for Joplin v2 (and CodeMirror 5).

---

In Joplin v3, they use CodeMirror 6 and [have included all the languages supported by CodeMirror 6.](https://github.com/laurent22/joplin/blob/0b6082d679a41ffa55fa015057a651714d2292c0/packages/editor/CodeMirror/markdown/codeBlockLanguages/allLanguages.ts)

The full list is here. Note that Clojure is included.

https://github.com/codemirror/language-data/blob/7b21009213b9fdb44d6ec172ad0a779234170f52/src/language-data.ts#L12-L1016

---

Currently, this plugin doesn't support Joplin v3 with CodeMirror 6, but I'm working on an update for it.

**Comment by chr15m** [comment]
Ah interesting, thanks! It's strange because I am running v3 but in the console it appears to be using codemirror 5, and clojure inside code blocks in markdown is definitely not highlighted. 🤔

**Comment by ckant** [comment]
Just pushed the update for Joplin v3 / CodeMirror 6.

Update the plugin to `2.0.0` and make sure this option is **unchecked** under `General`
<img width="661" alt="image" src="https://github.com/user-attachments/assets/7143b7bb-a6ce-4618-9269-5e7f4d6823e5">

**Comment by chr15m** [comment]
Thanks @ckant! I couldn't get this working and continued to see CM5 in the console:

**Comment by ckant** [comment]
np 👍
